### ISSUE TITLE
Adding ✔ and ✘

### ISSUE THREAD

**Issue by amine177** [danielmario/gohufont-powerline#2]
Would you please add the tow characters ✘ and ✔ ?
As this would make the font more usable with bash-git-status .

**Comment by limadm** [comment]
Sorry for the late reply.
Do you know which unicode codepoints are used?

**Comment by amine177** [comment]
the X :   U+2718
the other one : U+2714

**Comment by limadm** [comment]
I've added those six dingbats, namely, U+2713 to U+2718.
Could you check this branch: https://github.com/limadm/gohufont-powerline/tree/towchars?

**Comment by amine177** [comment]
It is nice, would you merge?

**Comment by limadm** [comment]
Yes, I'll add them to the TTF version too.
